version: 0
allowPullRequests: public
tasks:

  # The bors build queue (test suite)
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
        branches:
          - staging
          - trying
    payload:
      maxRunTime: 3600
      image: "notriddle/docker-phoenix-elixir-test@sha256:f3b3e932d2565135ac3d1efcb52f84ba72038228a6707638b533b1a0d9025e14"
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo &&
          git config advice.detachedHead false && git checkout {{event.head.sha}} &&
          (sudo runuser -u postgres -- /usr/lib/postgresql/9.5/bin/postgres -D /etc/postgresql/9.5/main/ 2>&1 > /dev/null &) &&
          sleep 2 &&
          export MIX_ENV=test &&
          mix do deps.get, test
    metadata:
      name: Bors-NG test suite
      description: 'Run unit and integration tests with no browser and a mock GitHub API'
      owner: 'infra@bors.tech'
      source: '{{ event.head.repo.url }}'

  # The bors build queue (static analysis)
  # TODO: cache the PLT files that dialyzer uses
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - push
        branches:
          - staging
          - trying
    payload:
      maxRunTime: 3600
      image: "notriddle/docker-phoenix-elixir-test@sha256:f3b3e932d2565135ac3d1efcb52f84ba72038228a6707638b533b1a0d9025e14"
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          export MIX_ENV=dev &&
          git clone {{event.head.repo.url}} repo && cd repo &&
          git config advice.detachedHead false && git checkout {{event.head.sha}} &&
          mix deps.get &&
          mix dialyzer --halt-exit-status
    metadata:
      name: Bors-NG static analysis
      description: 'Run static analysis (dialyzer)'
      owner: 'infra@bors.tech'
      source: '{{ event.head.repo.url }}'

  # The pull request builder (static analysis)
  - provisionerId: '{{ taskcluster.docker.provisionerId }}'
    workerType: '{{ taskcluster.docker.workerType }}'
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
        branches:
          - master
    payload:
      maxRunTime: 3600
      image: "notriddle/docker-phoenix-elixir-test@sha256:f3b3e932d2565135ac3d1efcb52f84ba72038228a6707638b533b1a0d9025e14"
      command:
        - /bin/bash
        - '--login'
        - '-c'
        - >-
          git clone {{event.head.repo.url}} repo && cd repo &&
          git config advice.detachedHead false && git checkout {{event.head.sha}} &&
          export MIX_ENV=dev &&
          mix deps.get &&
          mix dialyzer --halt-exit-status
    metadata:
      name: Bors-NG style checker
      description: 'Run "build" against a pull request'
      owner: '{{ event.head.user.email }}'
      source: '{{ event.head.repo.url }}'
