language: elixir
elixir:
  - 1.7.3
  - 1.8.1
otp_release:
  - 20.0
  - 21.0.9
branches:
    only:
      - master
      - staging
      - trying

services:
  - postgresql
  - mysql

cache:
  directories:
    - _build
    - deps

install:
  - mix do local.rebar --force, local.hex --force, deps.get

script:
  - if [[ "$ELIXIR_VERSION" = "1.8.1" ]]; then mix format --check-formatted; fi
  - mix test

env:
  - TYPE=test
  - TYPE=test BORS_TEST_DATABASE=mysql

matrix:
  fast_finish: true

notifications:
  email: false
