language: elixir
elixir:
  - 1.4.5
  - 1.5
otp_release:
  - 19.1
  - 20.0
branches:
    only:
      - master
      - staging
      - trying

cache:
  directories:
    - _build
    - deps

install:
  - mix do local.rebar --force, local.hex --force, deps.get

script:
  - mix test

env:
  - TYPE=test
  - TYPE=test BORS_TEST_DATABASE=mysql

matrix:
  fast_finish: true

notifications:
  email: false
